podio_api_key: 'issues'
podio_api_secret: 'QnVQnkCQkCBBsYiVWcdVpuQS3TlvYaDfc3xacXj9n2bNvULAYCOg4MM9TOV5LGaq'
podio_app_id: '9343326'
podio_app_token: '8a6c2571599e470d8dbaae867a70ce94'
git_login: 'CharlesChapman'
git_password: 'M@rket2009'